plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/Demian/Рабочий стол/my_site"
publishOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/ots/*"
to = "https://onetimesecret.com/api/v1/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]